KEYBOARD_ALGOLIA_ACCEPT = "✅ Да, проблема решена"
KEYBOARD_ALGOLIA_REFUSE = "❌ Нет, это не то"

KEYBOARD_SEND = "📩 Отправить"
KEYBOARD_PAGINATION_FORWARD = "Вперёд ➡️"
KEYBOARD_PAGINATION_BACKWARD = "⬅️ Назад"
KEYBOARD_PAGINATION_CREATE = "➕ Новый вопрос"
KEYBOARD_GO_BACK = "⬅️ Вернуться назад"

KEYBOARD_REQUEST_UNBLOCK = "👁️ Разблокировка"
KEYBOARD_REQUEST_COMPLAIN = "‼️ Жалоба"
KEYBOARD_REQUEST_NEW_FEATURE = "🧿 Предложение"
KEYBOARD_REQUESTS_HISTORY = "🗃 Архив"

KEYBOARD_AGREE_WITH_RULES = "✅ Я согласен"

KEYBOARD_MAIN_MENU_EDITOR = "✏️ Редактор"
KEYBOARD_MAIN_MENU_PROFILE = "👽 Профиль"
KEYBOARD_MAIN_MENU_SUPPORT = "🧐 Помощь"

KEYBOARD_PROFILE_INVITES = "🔗 Приглашения"
KEYBOARD_PROFILE_VIOLATIONS = "⛔ Нарушения"

KEYBOARD_SUPPORT_REQUEST = "🦉 Запрос"
KEYBOARD_SUPPORT_QUESTION = "❓ Вопрос"

KEYBOARD_UNBLOCK_ATTACH = "📎 Приложить сообщение"

KEYBOARD_TICKETS_REPLY = "📝 Ответить"
KEYBOARD_TICKETS_DIALOG = "✉️ Диалог"
KEYBOARD_GO_TO_TICKET = "❓ Открыть вопрос"
KEYBOARD_CLOSE_TICKET = "✅ Закрыть вопрос"

KEYBOARD_INVITE_CONFIRM = "✅ Да"
KEYBOARD_INVITE_REFUSE = "❌ Нет"
